cuhc/urls.py
from django.urls import path
from .views import *
from cuhc import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "cuhc"
urlpatterns = [
    path('',views.cuhcpage,name='home'),
     path("register/",
          EtudiantRegistrationView.as_view(), name="etudiantregistration"),

    path("logout/", EtudiantLogoutView.as_view(), name="etudiantlogout"),
    path("login/", EtudiantLoginView.as_view(), name="etudiantlogin"),

]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_cuch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cuhc.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.MEDIA_ROOT)

cuhc/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Etudiant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200, null=True, blank=True)
    birth_date = models.DateField(blank=True, null=True)

class article (models.Model):
    title=models.CharField(max_length=50)
    desc=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    pdf=models.FileField(upload_to='pdf/')

class images (models.Model):
    id_image=models.CharField(max_length=50)
    image=models.ImageField(upload_to='images/')
    

    def __str__(self):
        return self.full_name
    def __str__(self):
        return self.title
    def __str__(self):
        return self.id_image

cuhc/forms.py
from django import forms
from django.db.models.fields import CharField
from django.forms.widgets import Widget
from .models import Etudiant
from django.contrib.auth.models import User


class EtudiantRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())
    
    class Meta:
        model = Etudiant
        fields = ["username", "password", "email", "full_name", ]

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Etudiant with this username already exists.")

        return uname


class EtudiantLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

cuhc/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls.base import reverse_lazy
from django.views.generic.base import View
from django.shortcuts import redirect, render
from django.http import HttpResponse,JsonResponse
from django.template import loader
from django.views.generic.edit import CreateView, FormView
from .models import *
from .forms import *
from django.core.mail import message, send_mail

# Create your views here.
def cuhcpage(request):
    list_articles=article.objects.all()
    list_img=images.objects.all()
    context={"liste_articles":list_articles,"liste_img":list_img}
    return render(request,"index1.html",context)





class EtudiantRegistrationView(CreateView):
    template_name = "etudiantregistration.html"
    form_class = EtudiantRegistrationForm
    success_url = reverse_lazy('cuhc:home')

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url
class  EtudiantLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('cuhc:home')


class  EtudiantLoginView(FormView):
    template_name = "etudiantlogin.html"
    form_class = EtudiantLoginForm
    success_url = reverse_lazy('cuhc:home')

    # form_valid method is a type of post method and is available in createview formview and updateview
    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Etudiant.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})

        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url

def contact(request):
    if request.methode=="POST":
        message_name=request.POST['message_name']
        message_email=request.POST['message_email']
        subject=request.POST['subject']
        message=request.POST['message']

        send_mail(
            
        )

templates/base1.html
    {%load static%}
    {% block head %}
    <head>
    

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <title>{% block title %}الحي الجامعي بحمام الشط{% endblock %}</title>
    <!-- Favicons -->
  <link href="{%static 'assets/img/favicon.png'%}" rel="icon">
  <link href="{%static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">
    <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
  <link href="{%static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{%static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{%static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{%static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
  <link href="{%static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{%static 'assets/vendor/remixicon/remixicon.css'%}" rel="stylesheet">
  <link href="{%static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <script src="https://kit.fontawesome.com/c442c47365.js" crossorigin="anonymous"></script>
</head>
{%endblock%}

<body>
        <div id="content">{% block content %}{% endblock %}</div>
        <div id="footer">
            {% block footer %}
                &copy; Copyright 2021 by <a href="https://www.ooun.rnu.tn/">ديوان الخدمات الجامعيّة بالشمال</a>.
            {% endblock %}
        </div>
    </body>

templates/etudiantlogin.html
<html>
{% extends 'base1.html' %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>الدخول</h3>
            <hr>
            <form action="" method="POST">
                <div class="row">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">الارسال</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            <p> or dont have account? <a href="{% url 'cuhc:etudiantregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">الارسال</a></p>
        </div>
        </div>
    </div>
</div>
{% endblock %}
</html>

templates/etudiantregistration.html
{% extends 'base1.html' %}


{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3> <center>  تسجيل  الطلبة  </center> </h3><hr>
            <form action="" method="POST">
                <div class="row">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">تسجيل</button>
            </div>
            </form>
            <p> Already have an account? <a href="{% url 'cuhc:etudiantlogin' %}">دخول</a></p>
        </div>
    </div>
</div>
{% endblock %}